### ISSUE TITLE
Issue in https://github.com/suer/redmine_oauth_provider 

### ISSUE THREAD

**Issue by col-panic** [suer/ghstreaks#1]
Hy there,

I excuse for cross-posting here but you do not have an issue tracker in the redmine_oauth_provider repository :(

Could you please have a look at a bug I face there when installing according to your documentation:

https://gist.github.com/col-panic/3595bc4ffee861db5317/8a730ffb45203f99f85d21ea414f1de2f8bd4171

Thank you very much!

**Comment by suer** [comment]
It works for me with Redmine 3.1.0.
The other plugins may raise this error.
Please remove the other plugins, and re-run migration.

Thanks.

**Comment by col-panic** [comment]
Ok, a restart helps :)

**Comment by col-panic** [comment]
Hy Ryo,

thank you for your answer. Unfortunately this is not possible, as it 
forms a core function of Redmine. What makes me sad, however, is that 
the producer of the other plugin just gave me the same answer ...

well ...

thanks a lot :)
marco

Ryo SUETSUGU schrieb:

**Comment by suer** [comment]
Same problem is reported.

https://github.com/suer/redmine_oauth_provider/pull/4

This patch was merged well.

Could you try HEAD of master branch?

Thanks.

**Comment by col-panic** [comment]
The error is now different, occuring at another place in the code

```
rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
wrong number of arguments (3 for 2)
/var/lib/gems/1.9.1/gems/activerecord-3.2.17/lib/active_record/associations.rb:1197:in `has_many'
/home/server/services/redmine-2.4.3-beta/plugins/redmine_oauth_provider/lib/oauth_provider_user_patch.rb:8:in `block in included'
/home/server/services/redmine-2.4.3-beta/plugins/redmine_oauth_provider/lib/oauth_provider_user_patch.rb:4:in `class_eval'
/home/server/services/redmine-2.4.3-beta/plugins/redmine_oauth_provider/lib/oauth_provider_user_patch.rb:4:in `included'
/home/server/services/redmine-2.4.3-beta/plugins/redmine_oauth_provider/init.rb:16:in `include'
/home/server/services/redmine-2.4.3-beta/plugins/redmine_oauth_provider/init.rb:16:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:506:in `_run__121613957997973119__prepare__3306030111128612681__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/var/lib/gems/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/server/services/redmine-2.4.3-beta/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
root@mis:/srv/services/mis-redmine-beta# git log | more
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by col-panic** [comment]
It works when using Redmine 3.1.1 :) Could you consider to open an issue tab on the redmine_oauth_provider project? thanks a lot!!

**Comment by suer** [comment]
Required Redmine version in README of redmine_oauth_provider is Redmine 2.3 or later, but it seems wrong.
I will correct required version in README.

redmine_oauth_provider project is forked from other one. So it is difficult to support anyone.
But I consider to open issue tab positively.

Many thanks.
